"use client";
import { Bar, BarChart, CartesianGrid, Cell, Legend, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import ChartFrame from "./ChartFrame";

export default function GangProductivityChart({ data, onSelect }: { data: Array<{ key: string; date: string; gang: string; activity: string; unit: string; planned: number; actual: number; dailyOutput: number; gangSize: number; performance: number; status: string }>; onSelect?: (key: string) => void }) {
  return <ChartFrame title="Gang productivity" description="Daily gang/activity Man-Day Productivity, worst performance first." summary={data.length ? `${data[0].gang} is lowest at ${data[0].performance.toFixed(1)} percent, status ${data[0].status}.` : "No gang productivity data exists."}>
    <ResponsiveContainer width="100%" height="100%"><BarChart layout="vertical" data={data.slice(0, 10)} margin={{ top: 8, right: 12, bottom: 8, left: 36 }}><CartesianGrid strokeDasharray="3 3" horizontal={false} /><XAxis type="number" tick={{ fontSize: 11 }} /><YAxis type="category" dataKey="gang" width={82} tick={{ fontSize: 11 }} /><Tooltip content={({ active, payload }) => active && payload?.[0] ? <div className="dashboard-tooltip"><strong>{payload[0].payload.gang} · {payload[0].payload.date}</strong><span>{payload[0].payload.activity}</span><span>{payload[0].payload.actual.toFixed(2)} {payload[0].payload.unit}/man-day · {payload[0].payload.dailyOutput.toFixed(2)} {payload[0].payload.unit}/day · {payload[0].payload.gangSize} operatives</span><span>{payload[0].payload.performance.toFixed(1)}% · {payload[0].payload.status}</span></div> : null} /><Legend /><Bar dataKey="planned" name="Planned Man-Day Productivity" fill="#53788a" onClick={(entry) => onSelect?.((entry as unknown as { key: string }).key)} /><Bar dataKey="actual" name="Actual Man-Day Productivity" onClick={(entry) => onSelect?.((entry as unknown as { key: string }).key)}>{data.slice(0, 10).map((row) => <Cell key={row.key} fill={row.performance >= 100 ? "#1b8a5a" : row.performance >= 90 ? "#d0932b" : "#c84b3a"} />)}</Bar></BarChart></ResponsiveContainer>
  </ChartFrame>;
}
