"use client";
import { Bar, BarChart, CartesianGrid, Legend, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import ChartFrame from "./ChartFrame";

export default function PlannedVsActualChart({ data, unit, onSelect }: { data: Array<{ label: string; start: string; end: string; expected: number; actual: number; achievement: number | null }>; unit: string; onSelect?: (range: { label: string; start: string; end: string }) => void }) {
  const expected = data.reduce((sum, row) => sum + row.expected, 0), actual = data.reduce((sum, row) => sum + row.actual, 0);
  return <ChartFrame title="Planned vs achieved output" description="Expected and recorded quantities for the selected period." summary={`${actual.toFixed(1)} ${unit || "units"} achieved against ${expected.toFixed(1)} expected.`}>
    <ResponsiveContainer width="100%" height="100%"><BarChart data={data} margin={{ top: 8, right: 8, bottom: 8, left: 0 }}><CartesianGrid strokeDasharray="3 3" vertical={false} /><XAxis dataKey="label" tick={{ fontSize: 11 }} /><YAxis tick={{ fontSize: 11 }} /><Tooltip content={({ active, payload }) => active && payload?.[0] ? <div className="dashboard-tooltip"><strong>{payload[0].payload.label}</strong><span>Expected {Number(payload[0].payload.expected).toFixed(2)} {unit}</span><span>Achieved {Number(payload[0].payload.actual).toFixed(2)} {unit}</span><span>Variance {(Number(payload[0].payload.actual) - Number(payload[0].payload.expected)).toFixed(2)} {unit}</span><span>Achievement {payload[0].payload.achievement === null ? "—" : `${Number(payload[0].payload.achievement).toFixed(1)}%`}</span></div> : null} /><Legend /><Bar dataKey="expected" name="Expected Quantity" fill="#53788a" radius={[3,3,0,0]} onClick={(entry) => onSelect?.(entry as unknown as { label: string; start: string; end: string })} /><Bar dataKey="actual" name="Achieved Quantity" fill="#1b8a5a" radius={[3,3,0,0]} onClick={(entry) => onSelect?.(entry as unknown as { label: string; start: string; end: string })} /></BarChart></ResponsiveContainer>
  </ChartFrame>;
}
