"use client";
import { Bar, BarChart, CartesianGrid, Legend, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import ChartFrame from "./ChartFrame";

type OutputPoint = { label: string; start: string; end: string; expected: number; actual: number; achievement: number | null; productTypes?: string; gangSize?: number | null; productivityFactor?: number | null; disruptionHours?: number | null };
export default function PlannedVsActualChart({ data, unit, onSelect }: { data: OutputPoint[]; unit: string; onSelect?: (range: { label: string; start: string; end: string }) => void }) {
  const expected = data.reduce((sum, row) => sum + row.expected, 0), actual = data.reduce((sum, row) => sum + row.actual, 0);
  return <ChartFrame title="Daily output — planned vs achieved" description="Required and recorded output for each reporting interval." summary={`${actual.toFixed(1)} ${unit || "units"} achieved against ${expected.toFixed(1)} required.`}>
    <ResponsiveContainer width="100%" height="100%"><BarChart data={data} margin={{ top: 8, right: 8, bottom: 8, left: 0 }}><CartesianGrid strokeDasharray="3 3" vertical={false} /><XAxis dataKey="label" tick={{ fontSize: 11 }} /><YAxis tick={{ fontSize: 11 }} /><Tooltip content={({ active, payload }) => { const row = payload?.[0]?.payload as OutputPoint | undefined; return active && row ? <div className="dashboard-tooltip"><strong>{row.label}</strong>{row.productTypes && <span>Work type: {row.productTypes}</span>}<span>Required {row.expected.toFixed(2)} {unit}</span><span>Actual {row.actual.toFixed(2)} {unit}</span><span>Variance {(row.actual-row.expected).toFixed(2)} {unit}</span>{row.gangSize !== null && row.gangSize !== undefined && <span>Gang: {row.gangSize.toFixed(1)} operatives</span>}{row.productivityFactor !== null && row.productivityFactor !== undefined && <span>Productivity Factor: {row.productivityFactor.toFixed(2)} (lower is better)</span>}{row.disruptionHours !== null && row.disruptionHours !== undefined && <span>Disruption: {row.disruptionHours.toFixed(1)} labour hrs</span>}</div> : null; }} /><Legend /><Bar dataKey="expected" name="Required / Planned Output" fill="#53788a" radius={[3,3,0,0]} onClick={(entry) => onSelect?.(entry as unknown as { label: string; start: string; end: string })} /><Bar dataKey="actual" name="Actual Output" fill="#1b8a5a" radius={[3,3,0,0]} onClick={(entry) => onSelect?.(entry as unknown as { label: string; start: string; end: string })} /></BarChart></ResponsiveContainer>
  </ChartFrame>;
}
