"use client";
import { CartesianGrid, Legend, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import ChartFrame from "./ChartFrame";

type ProductivityPoint = { label: string; planned: number | null; actual: number | null; gangSize?: number | null; actualOutput?: number | null; disruptionHours?: number | null; productTypes?: string };
export default function ProductivityTrendChart({ data, unit }: { data: ProductivityPoint[]; unit: string }) {
  const valid = data.filter((row) => row.actual !== null);
  return <ChartFrame title="Man-Day Productivity" description={`Actual versus planned baseline in ${unit || "units"} per contributing operative per day.`} summary={valid.length ? `${valid.length} periods contain Actual Man-Day Productivity.` : "No linked operative productivity data exists for this period."}>
    <ResponsiveContainer width="100%" height="100%"><LineChart data={data} margin={{ top: 8, right: 12, bottom: 8, left: 0 }}><CartesianGrid strokeDasharray="3 3" vertical={false} /><XAxis dataKey="label" tick={{ fontSize: 11 }} /><YAxis tick={{ fontSize: 11 }} /><Tooltip content={({ active, payload }) => { const row = payload?.[0]?.payload as ProductivityPoint | undefined; return active && row ? <div className="dashboard-tooltip"><strong>{row.label}</strong>{row.productTypes && <span>Work type: {row.productTypes}</span>}<span>Actual productivity: {row.actual === null ? "Not available" : `${row.actual.toFixed(2)} ${unit}/man-day`}</span><span>Planned baseline: {row.planned === null ? "Not available" : `${row.planned.toFixed(2)} ${unit}/man-day`}</span>{row.gangSize !== null && row.gangSize !== undefined && <span>Gang: {row.gangSize.toFixed(1)} operatives</span>}{row.actualOutput !== null && row.actualOutput !== undefined && <span>Actual output: {row.actualOutput.toFixed(1)} {unit}</span>}{row.disruptionHours !== null && row.disruptionHours !== undefined && <span>Disruption: {row.disruptionHours.toFixed(1)} labour hrs</span>}</div> : null; }} /><Legend /><Line connectNulls type="monotone" dataKey="planned" name="Planned Man-Day Productivity" stroke="#53788a" strokeWidth={2} /><Line connectNulls type="monotone" dataKey="actual" name="Actual Man-Day Productivity" stroke="#1b8a5a" strokeWidth={3} /></LineChart></ResponsiveContainer>
  </ChartFrame>;
}
