"use client";
import Link from "next/link";
import { Bar, BarChart, CartesianGrid, Legend, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
export type HealthTone="green"|"amber"|"red"|"neutral";
export type HealthCard={title:string;value:string;detail:string;tone:HealthTone;href:string;support?:Array<{label:string;value:string}>};
export type PerformancePoint={label:string;start?:string;end?:string;plannedOutput:number;actualOutput:number;plannedProductivity:number|null;actualProductivity:number|null;cumulativePlanned:number;cumulativeActual:number;productType?:string;area?:string;gang?:string;gangSize?:number|null;disruptionHours?:number|null};
const icon:Record<HealthTone,string>={green:"●",amber:"▲",red:"■",neutral:"◇"};
const label:Record<HealthTone,string>={green:"Green",amber:"Amber",red:"Red",neutral:"Unavailable"};
export function TodayPlanCard({count,ready,amber,red,target,unit}:{count:number;ready:number;amber:number;red:number;target?:number|null;unit?:string}){return <Link href="/daily-plan" className="daily-plan-health"><div><p className="eyebrow">Today&apos;s plan</p><strong>{count?`${count} activities`:"No plan created"}</strong></div>{count?<><span>{ready} Ready · {amber} Amber · {red} Red</span><span>{target!=null?`Target: ${target.toLocaleString("en-GB",{maximumFractionDigits:1})} ${unit||""}`:"Target summary unavailable"}</span><b>Open →</b></>:<><span>Create the operational plan for the selected day.</span><span></span><b>Create Daily Plan →</b></>}</Link>}
export function HealthCards({cards}:{cards:HealthCard[]}){return <section className="health-status-grid" aria-label="Independent project health measures">{cards.map(card=><Link href={card.href} key={card.title} className={`health-status-card ${card.tone}`}><header><span>{card.title}</span><b>{icon[card.tone]} {label[card.tone]}</b></header><strong>{card.value}</strong><small>{card.detail}</small>{card.support&&<dl className="health-card-support">{card.support.map(row=><div key={row.label}><dt>{row.label}</dt><dd>{row.value}</dd></div>)}</dl>}</Link>)}</section>}
export function PeriodProgress({planned,actual,unit,tone,mixed}:{planned:number|null;actual:number|null;unit:string;tone:HealthTone;mixed:boolean}){const percent=planned&&actual!==null?actual/planned*100:null;return <section className="period-progress"><header><div><p className="eyebrow">Period progress</p><h2>Plan / Actual / Variance</h2></div><span className={`health-rag ${tone}`}>{icon[tone]} {percent===null?"Unavailable":`${percent.toLocaleString("en-GB",{maximumFractionDigits:1})}% of period plan`}</span></header>{mixed?<p className="health-neutral-state">Mixed units cannot be summed. Select an Interface / Product Type or unit-compatible Area.</p>:<div className="period-progress-values"><dl><dt>Plan</dt><dd>{planned===null?"—":`${planned.toLocaleString("en-GB",{maximumFractionDigits:1})} ${unit}`}</dd></dl><dl><dt>Actual</dt><dd>{actual===null?"—":`${actual.toLocaleString("en-GB",{maximumFractionDigits:1})} ${unit}`}</dd></dl><dl><dt>Variance</dt><dd>{planned===null||actual===null?"—":`${actual-planned>=0?"+":""}${(actual-planned).toLocaleString("en-GB",{maximumFractionDigits:1})} ${unit}`}</dd></dl></div>}</section>}
export function ProductionPerformance({view,setView,points,unit,compatible}:{view:string;setView:(value:string)=>void;points:PerformancePoint[];unit:string;compatible:boolean}){const common=<><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="label" tick={{fontSize:11}}/><YAxis tick={{fontSize:11}}/><Tooltip content={({active,payload})=>{const row=payload?.[0]?.payload as PerformancePoint|undefined;return active&&row?<div className="dashboard-tooltip"><strong>{row.label}</strong>{row.productType&&<span>Product Type: {row.productType}</span>}{row.area&&<span>Area: {row.area}</span>}{row.gang&&<span>Gang: {row.gang}</span>}<span>Required Quantity: {row.plannedOutput.toFixed(2)} {unit}</span><span>Actual Quantity: {row.actualOutput.toFixed(2)} {unit}</span>{row.plannedProductivity!==null&&<span>Required MD Productivity: {row.plannedProductivity.toFixed(2)} {unit}/MD</span>}{row.actualProductivity!==null&&<span>Actual MD Productivity: {row.actualProductivity.toFixed(2)} {unit}/MD</span>}{row.gangSize!=null&&<span>Gang Size: {row.gangSize.toFixed(1)}</span>}{row.disruptionHours!=null&&<span>Disruption: {row.disruptionHours.toFixed(1)} labour hrs</span>}</div>:null}}/><Legend/></>;
return <section className="production-performance"><header><div><p className="eyebrow">Production performance</p><h2>{view}</h2></div><label>View<select value={view} onChange={e=>setView(e.target.value)}><option>Daily Output</option><option>Man-Day Productivity</option><option>Cumulative Progress</option></select></label></header>{!compatible?<div className="health-chart-empty"><p>Select a Product Type to compare productivity and quantity without combining incompatible units.</p></div>:<div className="production-performance-chart"><ResponsiveContainer width="100%" height="100%">{view==="Daily Output"?<BarChart data={points}>{common}<Bar dataKey="plannedOutput" name="Required / Planned Output" fill="#53788a"/><Bar dataKey="actualOutput" name="Actual Output" fill="#1b8a5a"/></BarChart>:<LineChart data={points}>{common}{view==="Man-Day Productivity"?<><Line connectNulls dataKey="plannedProductivity" name="Planned MD Productivity" stroke="#53788a" strokeWidth={2}/><Line connectNulls dataKey="actualProductivity" name="Actual MD Productivity" stroke="#1b8a5a" strokeWidth={3}/></>:<><Line dataKey="cumulativePlanned" name="Cumulative Planned" stroke="#53788a" strokeWidth={2}/><Line dataKey="cumulativeActual" name="Cumulative Actual" stroke="#1b8a5a" strokeWidth={3}/></>}</LineChart>}</ResponsiveContainer></div>}</section>}
export function NeedsAttention({items}:{items:Array<{tone:"red"|"amber";text:string;href:string}>}){return <section className="health-attention"><header><p className="eyebrow">Exceptions</p><h2>Needs Attention</h2><p>Only supported, material exceptions for the current selection.</p></header>{items.length?<ol>{items.slice(0,5).map((item,index)=><li key={`${item.href}-${index}`}><Link href={item.href}><span className={`health-attention-rag ${item.tone}`}>{icon[item.tone]} {label[item.tone]}</span><strong>{item.text}</strong><span>→</span></Link></li>)}</ol>:<div className="health-all-clear"><span>●</span><div><strong>No current supported exceptions.</strong><p>No Red or Amber issue is evidenced for this selection.</p></div></div>}</section>}
