"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { sitepulseNavItems } from "@/components/BottomNav";
import { HealthCards, NeedsAttention, PeriodProgress, ProductionPerformance, TodayPlanCard, type HealthCard, type PerformancePoint } from "@/components/dashboard/ProjectHealthDashboard";
import { initialDemoState, type DemoState } from "@/lib/demoData";
const key="sitepulse-safe-demo-v2";
const pill=(value:string)=><span className={`readiness-pill ${value.toLowerCase()}`}>{value}</span>;
function Table({heads,rows}:{heads:string[];rows:React.ReactNode[][]}){return <div className="demo-table"><table><thead><tr>{heads.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((row,i)=><tr key={i}>{row.map((cell,j)=><td key={j}>{cell}</td>)}</tr>)}</tbody></table></div>}
export default function DemoReviewApp({initialView}:{initialView:string}){
 const [state,setState]=useState<DemoState>(initialDemoState),[product,setProduct]=useState("Curtain Wall"),[chart,setChart]=useState("Daily Output");
 useEffect(()=>{const saved=localStorage.getItem(key);if(saved)queueMicrotask(()=>setState(JSON.parse(saved)))},[]);
 useEffect(()=>{localStorage.setItem(key,JSON.stringify(state))},[state]);
 const activity=(id:string)=>state.activities.find(a=>a.id===id)!;
 const view=initialView==="/"?"/dashboard":initialView;
 const reset=()=>{localStorage.removeItem(key);setState(initialDemoState)};
 const series:Record<string,{unit:string;planned:number[];actual:number[];plannedMd:number;actualMd:number[];gang:string;area:string}>={"Curtain Wall":{unit:"m²",planned:[42,44,46,48,50],actual:[40,47,45,54,56],plannedMd:7,actualMd:[6.7,6.8,6.5,6.9,6.6],gang:"Gang A",area:"North"},"Composite Cladding":{unit:"m²",planned:[36,38,40,40,42],actual:[32,35,34,43,39],plannedMd:8,actualMd:[7.1,7.5,6.8,8.4,7.8],gang:"Gang B",area:"South"},Windows:{unit:"nr",planned:[6,7,8,8,9],actual:[5,8,7,9,8],plannedMd:2,actualMd:[1.7,2,1.8,2.2,2],gang:"Gang C",area:"East"}};
 const selectedSeries=series[product],performancePoints:PerformancePoint[]=selectedSeries.planned.map((plannedOutput,index)=>({label:["Mon","Tue","Wed","Thu","Fri"][index],plannedOutput,actualOutput:selectedSeries.actual[index],plannedProductivity:selectedSeries.plannedMd,actualProductivity:selectedSeries.actualMd[index],cumulativePlanned:selectedSeries.planned.slice(0,index+1).reduce((a,b)=>a+b,0),cumulativeActual:selectedSeries.actual.slice(0,index+1).reduce((a,b)=>a+b,0),productType:product,area:selectedSeries.area,gang:selectedSeries.gang,gangSize:[6,6,7,7,6][index],disruptionHours:[0,8,12,4,0][index]}));
 const demoCards:HealthCard[]=[{title:"Programme",value:"Key dates maintained",detail:"1 activity forecast late",tone:"green",href:"/programme"},{title:"Productivity Factor",value:"PF 1.06",detail:"6% more man-days consumed than earned",tone:"amber",href:"/reports",support:[{label:"Earned MD",value:"50"},{label:"Actual MD",value:"53"},{label:"Variance",value:"+3 MD"}]},{title:"Constraints",value:"2 Open · 1 Blocking",detail:"1 Red constraint",tone:"amber",href:"/constraints"},{title:"Disruption",value:"84 labour hrs",detail:"36.8% of recorded productive + lost hours",tone:"red",href:"/timeline"},{title:"Forecast",value:"1 activity forecast late",detail:"CW Glazing L04 highest risk",tone:"amber",href:"/forecast"},{title:"Change",value:"4 active changes",detail:"2 affecting planned works",tone:"amber",href:"/reports"}];
 const body=(()=>{
  if(view.startsWith("/programme"))return <><h1>Programme</h1><p>Fictional planner-controlled programme with predecessor relationships and milestones.</p><Table heads={["Activity","Product Type","Location","Planned Start","Finish","Quantity","Planned MD Productivity","Predecessor","Progress"]} rows={state.activities.map(a=>[<strong key={a.id}>{a.name}<small>{a.id}</small></strong>,a.product,a.area,a.start,a.finish,`${a.quantity||"—"} ${a.unit}`,a.plannedMd?`${a.plannedMd} ${a.unit}/MD`:"—",a.predecessor,`${a.progress}%`])}/></>;
  if(view.startsWith("/daily-plan"))return <><h1>Today / Daily Plan</h1><p>{state.date} · Committed morning allocations</p><div className="demo-grid">{state.allocations.map(a=><article key={a.id}><header><strong>{a.gang} · {a.operatives} operatives</strong>{pill(a.readiness)}</header><h3>{activity(a.activityId).name}</h3><p>{activity(a.activityId).area}</p><dl><div><dt>Planned MD Productivity</dt><dd>{activity(a.activityId).plannedMd} {activity(a.activityId).unit}/MD</dd></div><div><dt>Expected</dt><dd>{a.expected} {activity(a.activityId).unit}</dd></div><div><dt>Manager Target</dt><dd><input aria-label={`${a.gang} target`} type="number" value={a.target} onChange={e=>setState(s=>({...s,allocations:s.allocations.map(x=>x.id===a.id?{...x,target:Number(e.target.value),targetPf:a.expected/Number(e.target.value)}:x)}))}/></dd></div><div><dt>Target PF</dt><dd>{a.targetPf.toFixed(2)}</dd></div><div><dt>Actual</dt><dd>{a.actual} {activity(a.activityId).unit}</dd></div><div><dt>Actual PF</dt><dd>{a.actualPf.toFixed(2)}</dd></div></dl></article>)}</div><p className="demo-note">Gang A demonstrates a missed 48 m² target with 44 m² actual while actual PF 0.95 remains better than baseline.</p></>;
  if(view.startsWith("/attendance"))return <><h1>Attendance</h1><Table heads={["Operative","Fictional Company","Trade","Status","Gang"]} rows={[["Alex North","Demo Facades Ltd","Glazing","Signed in","Gang A"],["Jamie Vale","Demo Facades Ltd","Installer","Signed in","Gang A"],["Morgan Reed","Sample Cladding Ltd","Cladder","Signed in","Gang B"],["Taylor Stone","Sample Access Ltd","Plant Operator","Break","Gang C"]]}/></>;
  if(view.startsWith("/crews"))return <><h1>Gangs</h1><div className="demo-grid">{state.allocations.map(a=><article key={a.id}><h3>{a.gang}</h3><strong>{a.operatives} operatives</strong><p>{activity(a.activityId).name}</p><small>{activity(a.activityId).area}</small></article>)}</div></>;
  if(view.startsWith("/timeline"))return <><h1>Timeline</h1><p>{state.date} · Live site record</p><div className="demo-timeline">{[["07:30","Gang A started CW Glazing L04","Work · target 48 m²"],["10:15","Access restriction","Disruption · 4 labour hours"],["12:00","Lunch break","Break"],["14:40","Additional perimeter flashing","Change / VO · DEMO-VO-014"],["16:20","44 m² completed · 45m MEWP used","Work / plant usage"]].map(e=><article key={e[0]}><time>{e[0]}</time><div><strong>{e[1]}</strong><span>{e[2]}</span></div></article>)}</div></>;
  if(view.startsWith("/readiness"))return <><h1>Readiness / Release</h1><p>Live operational readiness remains separate from programme intent.</p><Table heads={["RAG","Activity","Predecessor","Release / Handover","Constraints","Site Status"]} rows={state.activities.slice(0,4).map(a=>[pill(a.id==="SP-D110"&&!state.handoverRecorded?"RED":a.rag),<strong key={a.id}>{a.name}<small>{a.id}</small></strong>,a.predecessor,a.id==="SP-D110"?(state.handoverRecorded?"North L04 handover recorded":"North L04 handover incomplete"):"Released",a.id==="SP-D110"?"1 RED":"None",a.id==="SP-D110"&&!state.handoverRecorded?"NOT READY":"READY"])}/><div className="demo-actions"><button className="primary-button" onClick={()=>setState(s=>({...s,handoverRecorded:true}))}>Record Demo Handover</button><button className="secondary-button" onClick={()=>setState(s=>({...s,exceptionRecorded:true}))}>Proceed with Exception</button></div>{state.exceptionRecorded&&<p className="demo-note">Exception recorded: controlled demonstration only—North L04 workface reviewed by Demo Site Manager.</p>}</>;
  if(view.startsWith("/constraints"))return <><h1>Constraints</h1><Table heads={["RAG","Status","Constraint ID","Activity","Programme Activity ID","Category","Owner","Required By","Days Open","Latest Update","Relationship"]} rows={state.constraints.map(c=>[pill(c.rag),c.status,c.id,activity(c.activityId).name,c.activityId,c.category,c.owner,c.required,c.days,c.update,c.relationship])}/></>;
  if(view.startsWith("/materials"))return <><h1>Materials</h1><p>Two-week call-off and readiness view</p><Table heads={["RAG","Material","Programme Activity","Required","Call-off","Expected Delivery","Status","Supplier"]} rows={[[pill("GREEN"),"Stick sections","SP-D100","10 Aug","03 Aug","09 Aug","Delivered","Demo Aluminium Ltd"],[pill("AMBER"),"Composite panels","SP-D200","17 Aug","Due today","16 Aug","Call-off due","Sample Panels Ltd"],[pill("RED"),"Vision glass","SP-D110","12 Aug","Overdue","15 Aug","Delivery after required date","Fictional Glass Ltd"]]}/></>;
  if(view.startsWith("/plant"))return <><h1>Plant</h1><Table heads={["RAG","Plant","Status","Gang","Activity","Last Used","Review"]} rows={[[pill("GREEN"),"45m MEWP","On Hire","Gang A","CW Glazing L04","Today","In use"],[pill("AMBER"),"26m MEWP","On Hire","Gang B","Composite Cladding L02","3 working days ago","Review utilisation"],[pill("RED"),"Telehandler",state.plantOffHireRequested?"Off-Hire Requested":"On Hire","—","—","7 working days ago","Off-hire opportunity"]]}/><button className="primary-button" onClick={()=>setState(s=>({...s,plantOffHireRequested:true}))}>Request Demo Off-Hire</button></>;
  if(view.startsWith("/reports"))return <><h1>Reports</h1><div className="demo-tabs"><button>Daily</button><button>Weekly</button><button>Monthly</button></div><Table heads={["Activity","Planned Quantity","Actual Quantity","Earned MD","Actual MD","MD Variance","PF","Constraint","Disruption","Plan Achievement"]} rows={[["CW Glazing L04","48 m²","44 m²","6.29","6.00","-0.29","0.95","1 RED","4 hrs","92%"],["Composite Cladding L02","38 m²","34 m²","4.25","5.00","+0.75","1.18","1 AMBER","—","89%"],["CW Stick L04","24 m²","25 m²","4.17","4.00","-0.17","0.96","None","—","104%"]]}/></>;
  if(view.startsWith("/forecast"))return <><h1>Forecast &amp; Recovery</h1><div className="demo-grid"><article>{pill("GREEN")}<h3>CW Stick L04</h3><strong>Healthy · finish 14 Aug</strong></article><article>{pill("RED")}<h3>CW Glazing L04</h3><strong>Likely finish: 24 Aug</strong><p>Recovery requirement: 49 m²/day</p></article><article>{pill("AMBER")}<h3>Composite Cladding L02</h3><strong>Recovery demonstrated</strong><p>Three sustained days above required output.</p></article><article>{pill("GREY")}<h3>Window Units L03</h3><strong>Insufficient data</strong></article></div></>;
  if(view.startsWith("/settings"))return <><h1>Settings</h1><p>Review-only configuration preview. PF thresholds: Green ≤ 1.00, Amber ≤ 1.10, Red &gt; 1.10.</p><button className="secondary-button" onClick={reset}>Reset Demo Data</button></>;
  return <main className="dashboard-page health-dashboard demo-shared-dashboard"><div className="dashboard-shell"><header className="health-header"><div><p className="eyebrow">Project health</p><h1>Project Health</h1><p>TEST-001 — SitePulse Demo · 10 Aug to 13 Aug 2026</p></div></header><TodayPlanCard count={5} ready={3} amber={1} red={1} target={150} unit="m²"/><HealthCards cards={demoCards}/><PeriodProgress planned={50} actual={56} unit="m²" tone="green" mixed={false}/><section className="health-compact-filters"><strong>Production performance</strong><label>Date range<select><option>Weekly</option><option>Daily</option><option>Monthly</option></select></label><label>To date<input type="date" value={state.date} readOnly/></label><label>Interface / Product Type<select value={product} onChange={e=>setProduct(e.target.value)}>{Object.keys(series).map(x=><option key={x}>{x}</option>)}</select></label><label>Area<select value={selectedSeries.area} disabled><option>{selectedSeries.area}</option></select></label><label>Gang<select value={selectedSeries.gang} disabled><option>{selectedSeries.gang}</option></select></label></section><ProductionPerformance view={chart} setView={setChart} points={performancePoints} unit={selectedSeries.unit} compatible={true}/><NeedsAttention items={[{tone:"red",text:"Glass delivery blocking CW Glazing L04.",href:"/constraints"},{tone:"red",text:"East Elevation handover not released.",href:"/readiness"},{tone:"amber",text:"Composite Cladding PF is 1.12.",href:"/reports"},{tone:"amber",text:"84 disruption labour hours recorded.",href:"/timeline"},{tone:"amber",text:"1 activity forecast late.",href:"/forecast"}]}/></div></main>;
 })();
 return <main className="demo-review"><header className="sitepulse-app-header"><Link className="sitepulse-brand" href="/dashboard">SitePulse</Link><span>TEST-001 — SitePulse Demo</span><strong className="demo-mode-badge">Demo / Review Mode</strong></header><nav className="primary-nav">{sitepulseNavItems.map(item=><Link className={`primary-nav-item ${view.startsWith(item.href)?"active":""}`} href={item.href} key={item.href}>{item.label}</Link>)}</nav><nav className="mobile-nav">{sitepulseNavItems.filter(i=>["/daily-plan","/attendance","/timeline"].includes(i.href)).map(item=><Link className="mobile-nav-item" href={item.href} key={item.href}><span>{item.icon}</span><span>{item.label.replace(" / Daily Plan","")}</span></Link>)}<Link className="mobile-nav-item" href="/settings"><span>•••</span><span>More</span></Link></nav><section className="demo-context"><strong>PROJECT</strong><span>TEST-001 — SitePulse Demo</span><time>{state.date}</time><button onClick={reset}>Reset Demo Data</button></section><section className="demo-content"><p className="demo-banner">Fictional, browser-local review data · No production database connection</p>{body}</section></main>;
}
