"use client";
import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { activityReadiness, type ActivityReadiness, type ReadinessData, type ReleaseStatus, type ReleaseType } from "@/lib/readiness";
import { getActiveDate, getActiveProjectId } from "@/lib/storage";
import { loadConstraintLinks, loadConstraints } from "@/lib/supabase/constraintData";
import { loadProjectRole, loadPublishedProgramme, loadPublishedProgrammeRelationships } from "@/lib/supabase/programmeData";
import { createOperationalDependency, createRelease, loadReadinessData, markSiteComplete } from "@/lib/supabase/readinessData";
import type { ConstraintActivityLink, ConstraintRecord } from "@/lib/constraints";
import type { ProgrammeActivity } from "@/types/site";
import LinkedEvidence from "@/components/evidence/LinkedEvidence";

const empty: ReadinessData = { releases: [], releaseLinks: [], dependencies: [], completions: [], exceptions: [], evidence: [], audit: [] };
const releaseTypes: ReleaseType[] = ["Client Handover", "Main Contractor Handover", "Area Release", "Access Release", "Predecessor Completion", "Design Release", "Inspection / Approval", "Other"];
const statuses: ReleaseStatus[] = ["NOT RELEASED", "PARTIALLY RELEASED", "RELEASED", "REVOKED"];
const activityLabel = (row: ProgrammeActivity) => `${row.programmeActivityId} · ${row.activity}`;
const errorMessage = (caught: unknown, fallback: string) => caught instanceof Error ? caught.message : caught && typeof caught === "object" && "message" in caught ? String(caught.message) : fallback;

export default function ReadinessPage() {
  const [activities,setActivities]=useState<ProgrammeActivity[]>([]),[relationships,setRelationships]=useState<Awaited<ReturnType<typeof loadPublishedProgrammeRelationships>>>([]),[data,setData]=useState<ReadinessData>(empty),[constraints,setConstraints]=useState<ConstraintRecord[]>([]),[links,setLinks]=useState<ConstraintActivityLink[]>([]);
  const [role,setRole]=useState<string>(),[loading,setLoading]=useState(true),[error,setError]=useState(""),[search,setSearch]=useState(""),[rag,setRag]=useState(""),[showRelease,setShowRelease]=useState(false),[showDependency,setShowDependency]=useState(false),[selected,setSelected]=useState<ActivityReadiness|null>(null);
  const [form,setForm]=useState({releaseType:"Area Release" as ReleaseType,title:"",activityIds:[] as string[],building:"",elevation:"",level:"",areaZone:"",description:"",plannedDate:"",actualDate:"",releasedBy:"",organisation:"",reference:"",status:"NOT RELEASED" as ReleaseStatus,notes:""}),[files,setFiles]=useState<File[]>([]);
  const [dependency,setDependency]=useState({predecessorId:"",successorId:"",description:""});
  const projectId=getActiveProjectId(),today=getActiveDate(),canWrite=Boolean(role),canConfigure=Boolean(role);
  async function reload(){setLoading(true);setError("");try{const [programme,rels,readiness,constraintRows,constraintLinks,memberRole]=await Promise.all([loadPublishedProgramme(projectId),loadPublishedProgrammeRelationships(projectId),loadReadinessData(projectId),loadConstraints(projectId),loadConstraintLinks(projectId),loadProjectRole(projectId)]);setActivities(programme.activities);setRelationships(rels);setData(readiness);setConstraints(constraintRows);setLinks(constraintLinks);setRole(memberRole);}catch(caught){setError(caught instanceof Error?caught.message:"Unable to load readiness.");}finally{setLoading(false)}}
  useEffect(()=>{queueMicrotask(()=>void reload())},[]); // eslint-disable-line react-hooks/exhaustive-deps
  const rows=useMemo(()=>activities.map(activity=>({activity,readiness:activityReadiness({activity,activities,relationships,data,constraints,constraintLinks:links,today})})).filter(({activity,readiness})=>(!search||`${activity.programmeActivityId} ${activity.activity} ${activity.building} ${activity.elevation} ${activity.level}`.toLowerCase().includes(search.toLowerCase()))&&(!rag||readiness.rag===rag)).sort((a,b)=>({RED:0,AMBER:1,GREEN:2,GREY:3}[a.readiness.rag]-{RED:0,AMBER:1,GREEN:2,GREY:3}[b.readiness.rag])),[activities,relationships,data,constraints,links,today,search,rag]);
  async function saveRelease(){try{if(!form.title.trim())throw new Error("Enter a release / handover title.");await createRelease(projectId,{...form,files});const affectedConstraintIds=new Set(links.filter(link=>form.activityIds.includes(link.programme_activity_external_id)).map(link=>link.constraint_id));const related=constraints.filter(row=>affectedConstraintIds.has(row.id)&&!["CLOSED","DISMISSED"].includes(row.status)&&["Access","Preceding Trade","Permits / Approvals","Design Information"].includes(row.category));setShowRelease(false);setFiles([]);setForm({...form,title:"",activityIds:[],areaZone:"",description:"",reference:"",notes:""});await reload();if(form.status==="RELEASED"&&related.length&&window.confirm(`Related release constraints may now be resolved (${related.length}). Review them for closure?`))window.location.assign(`/constraints?activity=${encodeURIComponent(form.activityIds[0])}`)}catch(caught){setError(errorMessage(caught,"Unable to save release."))}}
  async function complete(activity:ProgrammeActivity){const notes=window.prompt(`Site completion note for ${activity.activity} (optional):`)??undefined;if(notes===undefined)return;try{await markSiteComplete(projectId,activity.programmeActivityId,`${today}T12:00:00`,notes);await reload()}catch(caught){setError(caught instanceof Error?caught.message:"Unable to mark Site Complete.")}}
  async function saveDependency(){try{await createOperationalDependency(projectId,dependency.predecessorId,dependency.successorId,dependency.description);setShowDependency(false);setDependency({predecessorId:"",successorId:"",description:""});await reload()}catch(caught){setError(caught instanceof Error?caught.message:"Unable to save dependency.")}}
  const selectedActivity=selected?activities.find(row=>row.programmeActivityId===selected.activityId):undefined;
  return <main className="readiness-page"><div className="readiness-shell"><header className="readiness-header"><div><p className="eyebrow">Live site control</p><h1>Readiness / Release</h1><p>Programme intent and SitePulse operational facts are available to all project members.</p></div><div>{canConfigure&&<button className="secondary-button" onClick={()=>setShowDependency(true)}>Operational Dependency</button>}{canWrite&&<button className="primary-button" onClick={()=>setShowRelease(true)}>Record Handover</button>}</div></header>
  {error&&<p className="dashboard-notice error" role="alert">{error}</p>}{loading&&<p className="dashboard-notice">Loading live readiness…</p>}
  <section className="readiness-summary">{["RED","AMBER","GREEN"].map(tone=><article key={tone} className={tone.toLowerCase()}><span>{tone}</span><strong>{rows.filter(row=>row.readiness.rag===tone).length}</strong><small>{tone==="RED"?"Not ready":tone==="AMBER"?"Partial / started":"Ready / complete"}</small></article>)}</section>
  <section className="readiness-filters"><label>Search<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Activity, ID or location" /></label><label>RAG<select value={rag} onChange={e=>setRag(e.target.value)}><option value="">All</option><option>RED</option><option>AMBER</option><option>GREEN</option></select></label></section>
  <section className="report-table-scroll readiness-table"><table><thead><tr>{["RAG","Building","Elevation","Level","Programme Activity","Activity ID","Planned Start","Site Readiness","Predecessors","Release / Handover","Materials","Plant","Open Blockers","Actual Start","Site Complete","Action"].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map(({activity,readiness})=><tr key={activity.id}><td><span className={`readiness-pill ${readiness.rag.toLowerCase()}`}>{readiness.rag}</span></td><td>{activity.building||"—"}</td><td>{activity.elevation||"—"}</td><td>{activity.level||"—"}</td><td><strong>{activity.activity}</strong></td><td>{activity.programmeActivityId}</td><td>{activity.plannedStart||"—"}</td><td>{readiness.status}</td>{readiness.requirements.slice(0,5).map(item=><td key={item.key}><span className={`readiness-dot ${item.rag.toLowerCase()}`}>●</span> {item.detail}</td>)}<td>{activity.actualStart||"—"}</td><td>{readiness.siteCompletedAt?.slice(0,10)||"—"}</td><td><button className="table-action" onClick={()=>setSelected(readiness)}>View</button></td></tr>)}</tbody></table></section>
  <section className="readiness-mobile">{rows.map(({activity,readiness})=><article key={activity.id}><header><span className={`readiness-pill ${readiness.rag.toLowerCase()}`}>{readiness.rag} · {readiness.status}</span><strong>{activity.activity}</strong></header><p>{activity.programmeActivityId} · {[activity.building,activity.elevation,activity.level].filter(Boolean).join(" / ")}</p><p>{readiness.blockers[0]||"No known blocking item."}</p><button className="table-action" onClick={()=>setSelected(readiness)}>Readiness detail</button></article>)}</section>
  {!rows.length&&!loading&&<div className="constraint-empty-state"><h2>No matching programme activities</h2><p>Publish a programme or change the filters.</p></div>}
  {selected&&selectedActivity&&<LinkedEvidence context={{projectId,programmeActivityId:selectedActivity.programmeActivityId,activityName:selectedActivity.activity,building:selectedActivity.building,elevation:selectedActivity.elevation,level:selectedActivity.level,productType:selectedActivity.productType,recordType:"programme_activity",recordId:selectedActivity.programmeActivityId,category:"Handover"}} allowUpload={canWrite}/>}
  {selected&&selectedActivity&&<div className="readiness-backdrop"><section className="readiness-modal"><header><div><p className="eyebrow">Operational readiness</p><h2>{selectedActivity.activity}</h2><p>{selectedActivity.programmeActivityId}</p></div><button onClick={()=>setSelected(null)} aria-label="Close">×</button></header><div className="readiness-vs"><article><small>Programme</small><strong>{selectedActivity.status||selectedActivity.activityStatus||"—"}</strong><span>Planned {selectedActivity.plannedStart||"—"} → {selectedActivity.plannedFinish||"—"}</span><span>Actual start {selectedActivity.actualStart||"—"}</span></article><article><small>Live Site Readiness</small><strong>{selected.status}</strong><span>Handover / release {selected.actualRelease||"Not recorded"}</span><span>Site complete {selected.siteCompletedAt?.slice(0,10)||"Not recorded"}</span></article></div><section className="readiness-predecessor-detail"><strong>Imported programme predecessors</strong>{relationships.filter(row=>row.successorId===selectedActivity.programmeActivityId).length?<ul>{relationships.filter(row=>row.successorId===selectedActivity.programmeActivityId).map((row,index)=>{const predecessor=activities.find(activity=>activity.programmeActivityId===row.predecessorId);return <li key={`${row.predecessorId}-${index}`}>{predecessor?.activity||row.predecessorId} · {row.type}{row.lag?` · Lag ${row.lag}`:""}</li>})}</ul>:<p>No incoming predecessor relationship was imported for this activity. Add an Operational Readiness Dependency only where the site sequence requires one.</p>}</section><div className="readiness-requirements">{selected.requirements.map(item=><article key={item.key}><span className={`readiness-dot ${item.rag.toLowerCase()}`}>●</span><div><strong>{item.label}</strong><p>{item.detail}</p></div></article>)}</div>{selected.blockers.length>0&&<div className="readiness-warning"><strong>Blocking items</strong><ul>{selected.blockers.map(item=><li key={item}>{item}</li>)}</ul></div>}<footer>{canWrite&&selected.status!=="COMPLETE"&&<button className="secondary-button" onClick={()=>void complete(selectedActivity)}>Mark Site Complete</button>}<button className="primary-button" onClick={()=>{setForm(current=>({...current,title:`${selectedActivity.activity} handover`,activityIds:[selectedActivity.programmeActivityId],building:selectedActivity.building,elevation:selectedActivity.elevation,level:selectedActivity.level,plannedDate:selectedActivity.plannedStart||""}));setSelected(null);setShowRelease(true)}}>Record Handover</button></footer></section></div>}
  {showRelease&&<div className="readiness-backdrop"><section className="readiness-modal"><header><div><p className="eyebrow">Live site record</p><h2>Release / Handover</h2></div><button onClick={()=>setShowRelease(false)}>×</button></header><div className="readiness-form"><label>Release Type<select value={form.releaseType} onChange={e=>setForm({...form,releaseType:e.target.value as ReleaseType})}>{releaseTypes.map(value=><option key={value}>{value}</option>)}</select></label><label>Status<select value={form.status} onChange={e=>setForm({...form,status:e.target.value as ReleaseStatus})}>{statuses.map(value=><option key={value}>{value}</option>)}</select></label><label className="wide">Title *<input value={form.title} onChange={e=>setForm({...form,title:e.target.value})} /></label><label className="wide">Activities released *<select multiple value={form.activityIds} onChange={e=>setForm({...form,activityIds:[...e.target.selectedOptions].map(option=>option.value)})}>{activities.map(row=><option value={row.programmeActivityId} key={row.id}>{activityLabel(row)}</option>)}</select><small>Use Ctrl/Cmd to select more than one.</small></label>{[["Building","building"],["Elevation","elevation"],["Level","level"],["Release Area / Zone","areaZone"],["Released By","releasedBy"],["Responsible Organisation","organisation"],["Reference","reference"]].map(([label,key])=><label key={key}>{label}<input value={String(form[key as keyof typeof form])} onChange={e=>setForm({...form,[key]:e.target.value})}/></label>)}<label>Planned / Required Date<input type="date" value={form.plannedDate} onChange={e=>setForm({...form,plannedDate:e.target.value})}/></label><label>Actual Release Date<input type="date" value={form.actualDate} onChange={e=>setForm({...form,actualDate:e.target.value})}/></label><label className="wide">Description<textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><label className="wide">Notes<textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label><label className="wide">Evidence<input type="file" multiple accept="image/*,.pdf,.doc,.docx" onChange={e=>setFiles([...e.target.files||[]])}/><small>{files.length?`${files.length} file(s) selected`:"Signed sheet, PDF, photograph, inspection record or certificate"}</small></label></div><footer><button className="secondary-button" onClick={()=>setShowRelease(false)}>Cancel</button><button className="primary-button" onClick={()=>void saveRelease()}>Save Operational Record</button></footer></section></div>}
  {showDependency&&<div className="readiness-backdrop"><section className="readiness-modal small"><header><div><p className="eyebrow">SitePulse-only logic</p><h2>Operational Readiness Dependency</h2><p>This does not alter P6/Asta relationships.</p></div><button onClick={()=>setShowDependency(false)}>×</button></header><div className="readiness-form"><label className="wide">Activity A — must be released first<select value={dependency.predecessorId} onChange={e=>setDependency({...dependency,predecessorId:e.target.value})}><option value="">Select</option>{activities.map(row=><option value={row.programmeActivityId} key={row.id}>{activityLabel(row)}</option>)}</select></label><label className="wide">Activity B — downstream activity<select value={dependency.successorId} onChange={e=>setDependency({...dependency,successorId:e.target.value})}><option value="">Select</option>{activities.map(row=><option value={row.programmeActivityId} key={row.id}>{activityLabel(row)}</option>)}</select></label><label className="wide">Reason / description<textarea value={dependency.description} onChange={e=>setDependency({...dependency,description:e.target.value})}/></label></div><footer><button className="secondary-button" onClick={()=>setShowDependency(false)}>Cancel</button><button className="primary-button" disabled={!dependency.predecessorId||!dependency.successorId} onClick={()=>void saveDependency()}>Save Dependency</button></footer></section></div>}
  <p className="readiness-note">Operational records survive weekly programme imports because links use stable Programme Activity IDs. Planner actuals and SitePulse operational actuals are shown separately.</p><Link href="/programme" className="secondary-button">View controlled programme</Link>
  </div></main>;
}
