"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { useSearchParams } from "next/navigation";
import { Bar, BarChart, CartesianGrid, Cell, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import ProductivityRagBadge from "@/components/ProductivityRagBadge";
import { classifyDashboardBlocker } from "@/lib/dashboard";
import { getActiveDate, getActiveProject, getActiveProjectId } from "@/lib/storage";
import { loadPublishedProgramme, loadPublishedProgrammeRelationships } from "@/lib/supabase/programmeData";
import { loadTimelineEventsBetween } from "@/lib/supabase/timelineData";
import { downstreamImpact, floatAssessment, forecastScenario, historicalDisruptionStatistics, recentActuals, recoveryRequirement, workingDayVariance, workingDaysBetween, type ForecastRelationship, type ScenarioAssumptions } from "@/lib/scenarioForecast";
import { productivityPerformance, productivityRag } from "@/lib/productivityRag";
import type { ProgrammeActivity, TimelineEvent } from "@/types/site";

const format = (value: number | null | undefined, suffix = "") => value === null || value === undefined || !Number.isFinite(value) ? "—" : `${value.toLocaleString("en-GB", { maximumFractionDigits: 2 })}${suffix}`;
const formatDate = (value: string | null | undefined) => value ? new Intl.DateTimeFormat("en-GB", { day: "numeric", month: "short", year: "numeric" }).format(new Date(`${value}T12:00:00`)) : "—";
const unique = (values: Array<string | undefined>) => [...new Set(values.filter((value): value is string => Boolean(value)))].sort();
type DatedEvent = { date: string; event: TimelineEvent };

export default function ScenariosPage() {
  const params = useSearchParams();
  const [activities, setActivities] = useState<ProgrammeActivity[]>([]), [events, setEvents] = useState<DatedEvent[]>([]), [relationships, setRelationships] = useState<ForecastRelationship[]>([]);
  const [selectedId, setSelectedId] = useState(""), [selectedScenario, setSelectedScenario] = useState("Current Trend"), [loading, setLoading] = useState(true), [error, setError] = useState("");
  const [filters, setFilters] = useState({ building: "", elevation: "", level: "", productType: "" });
  const [edits, setEdits] = useState<Record<string, Partial<ScenarioAssumptions>>>({});
  const dataDate = getActiveDate();

  useEffect(() => { let cancelled = false; async function load() { try { const projectId = getActiveProjectId(); const [programme, timeline, logic] = await Promise.all([loadPublishedProgramme(projectId), loadTimelineEventsBetween(projectId, "1000-01-01", dataDate), loadPublishedProgrammeRelationships(projectId)]); if (cancelled) return; setActivities(programme.activities); setEvents(timeline); setRelationships(logic); const requested = params.get("activity"); setSelectedId(requested && programme.activities.some((row) => row.programmeActivityId === requested) ? requested : programme.activities[0]?.programmeActivityId ?? ""); } catch (caught) { if (!cancelled) setError(caught instanceof Error ? caught.message : "Unable to load scenario data."); } finally { if (!cancelled) setLoading(false); } } void load(); return () => { cancelled = true; }; }, [dataDate, params]);

  const options = useMemo(() => ({ buildings: unique(activities.map((row) => row.building)), elevations: unique(activities.filter((row) => !filters.building || row.building === filters.building).map((row) => row.elevation)), levels: unique(activities.filter((row) => (!filters.building || row.building === filters.building) && (!filters.elevation || row.elevation === filters.elevation)).map((row) => row.level)), productTypes: unique(activities.map((row) => row.productType)) }), [activities, filters.building, filters.elevation]);
  const filteredActivities = useMemo(() => activities.filter((row) => (!filters.building || row.building === filters.building) && (!filters.elevation || row.elevation === filters.elevation) && (!filters.level || row.level === filters.level) && (!filters.productType || row.productType === filters.productType)), [activities, filters]);
  const activity = activities.find((row) => row.programmeActivityId === selectedId) ?? filteredActivities[0];

  const model = useMemo(() => {
    if (!activity) return null;
    const activityEvents = events.filter(({ event }) => event.type === "work" && event.status === "completed" && event.programmeActivityId === activity.programmeActivityId && typeof event.quantity === "number");
    const productive = activityEvents.map(({ date, event }) => ({ date, quantity: Number(event.quantity), operatives: new Set(event.affectedOperativeIds ?? []).size || Number(event.numberOfOperatives ?? 0) }));
    const recent = recentActuals(productive, 10), cumulativeQuantity = productive.reduce((sum, row) => sum + row.quantity, 0), remainingQuantity = Math.max(Number(activity.plannedQuantity ?? 0) - cumulativeQuantity, 0);
    const disruptionRows = events.filter(({ event }) => event.type === "disruption" && event.programmeActivityId === activity.programmeActivityId).map(({ date, event }) => ({ date, category: classifyDashboardBlocker(event), lostLabourHours: Number(event.lostLabourHours ?? 0) }));
    const relevantStart = productive.map((row) => row.date).sort()[0] ?? disruptionRows.map((row) => row.date).sort()[0];
    const disruptionStats = historicalDisruptionStatistics(disruptionRows, relevantStart, dataDate);
    const relevantDays = relevantStart ? workingDaysBetween(relevantStart, dataDate) : 0, affectedDays = new Set(disruptionRows.map((row) => row.date)).size;
    const historicalExposure = relevantDays ? Math.min(80, affectedDays / relevantDays * 100) : 0;
    const currentProductivity = recent.productivity, currentGang = recent.effectiveGangSize ?? activity.assumedGangSize ?? 0;
    const planned = Number(activity.plannedManDayProductivity ?? 0), bestChange = currentProductivity && planned > 0 ? Math.max(0, (planned / currentProductivity - 1) * 100) : 15;
    const defaults: ScenarioAssumptions[] = [
      { name: "Current Trend", productivityChangePercent: 0, gangSize: currentGang, disruptionExposurePercent: historicalExposure, weekendWorking: false },
      { name: "Recovery", productivityChangePercent: 25, gangSize: Math.max(Math.ceil(currentGang), 1), disruptionExposurePercent: Math.max(historicalExposure - 10, 0), weekendWorking: false },
      { name: "Best Case", productivityChangePercent: Math.min(bestChange, 100), gangSize: Math.max(Math.ceil(currentGang), 1), disruptionExposurePercent: 0, weekendWorking: false },
      { name: "Downside", productivityChangePercent: -10, gangSize: Math.max(Math.floor(currentGang), 1), disruptionExposurePercent: Math.min(historicalExposure + 10, 80), weekendWorking: false },
    ];
    const assumptions = defaults.map((row) => ({ ...row, ...edits[row.name], name: row.name }));
    const forecasts = assumptions.map((assumption) => ({ assumption, result: forecastScenario({ id: activity.programmeActivityId, name: activity.activity, productType: activity.productType, plannedQuantity: activity.plannedQuantity, plannedFinish: activity.plannedFinish, plannedManDayProductivity: activity.plannedManDayProductivity, assumedGangSize: activity.assumedGangSize, calendar: activity.calendar }, dataDate, cumulativeQuantity, currentProductivity, assumption) }));
    const active = forecasts.find((row) => row.assumption.name === selectedScenario) ?? forecasts[0];
    const recovery = recoveryRequirement({ id: activity.programmeActivityId, name: activity.activity, plannedFinish: activity.plannedFinish }, dataDate, remainingQuantity, currentProductivity, active.assumption.gangSize, active.assumption.disruptionExposurePercent, active.assumption.weekendWorking);
    const successorStarts = new Map(activities.map((row) => [row.programmeActivityId, row.plannedStart]));
    const logic = relationships.map((row) => ({ ...row, successorPlannedStart: successorStarts.get(row.successorId) }));
    return { activityEvents, recent, cumulativeQuantity, remainingQuantity, disruptionStats, historicalExposure, currentProductivity, currentGang, assumptions, forecasts, active, recovery, downstream: downstreamImpact(activity.programmeActivityId, active.result.forecastFinish, logic), float: floatAssessment(active.result.daysEarlyLate, undefined) };
  }, [activities, activity, dataDate, edits, events, relationships, selectedScenario]);

  if (loading) return <main className="timeline-page"><section className="timeline-panel"><p>Loading scenario engine…</p></section></main>;
  if (error) return <main className="timeline-page"><section className="timeline-panel"><p role="alert">{error}</p></section></main>;
  if (!activity || !model) return <main className="timeline-page"><section className="timeline-panel"><p>No programme activities are available.</p></section></main>;
  const active = model.active, rag = productivityRag(activity.plannedManDayProductivity, model.currentProductivity), performance = productivityPerformance(activity.plannedManDayProductivity, model.currentProductivity);
  const update = (field: keyof ScenarioAssumptions, value: number | boolean) => setEdits((current) => ({ ...current, [selectedScenario]: { ...(current[selectedScenario] ?? {}), [field]: value } }));
  const currentFinish = model.forecasts[0].result.forecastFinish;

  return <main className="scenario-page"><div className="scenario-shell">
    <header className="scenario-header"><div><p className="eyebrow">Deterministic planning</p><h1>Scenario &amp; Forecast Engine</h1><p>{getActiveProject()?.name ?? "Project"} · data date {formatDate(dataDate)}</p></div><Link href="/dashboard" className="secondary-button">Back to Dashboard</Link></header>
    <section className="scenario-filters" aria-label="Scenario filters">{([ ["building", "Building", options.buildings], ["elevation", "Elevation", options.elevations], ["level", "Level", options.levels], ["productType", "Product Type", options.productTypes] ] as const).map(([key, label, values]) => <label key={key}><span>{label}</span><select value={filters[key]} onChange={(event) => setFilters((current) => ({ ...current, [key]: event.target.value }))}><option value="">All</option>{values.map((value) => <option key={value}>{value}</option>)}</select></label>)}<label><span>Activity</span><select value={activity.programmeActivityId} onChange={(event) => setSelectedId(event.target.value)}>{filteredActivities.map((row) => <option key={row.programmeActivityId} value={row.programmeActivityId}>{row.activity}</option>)}</select></label></section>

    <section className="scenario-hero"><div><span>Selected activity</span><h2>{activity.activity}</h2><p>{activity.building} / {activity.elevation} / {activity.level} · {activity.productType || "Product type missing"}</p></div><div><span>Programme finish</span><strong>{formatDate(activity.plannedFinish)}</strong></div><div><span>Current trend forecast</span><strong>{formatDate(currentFinish)}</strong><small>{model.forecasts[0].result.available ? `${format(model.forecasts[0].result.daysEarlyLate, " working days")} vs programme` : "Forecast unavailable – insufficient data."}</small></div><div><span>Productivity RAG</span><ProductivityRagBadge status={rag} /><small>{format(performance, "% of planned")}</small></div></section>

    <section className="scenario-workbench"><div><h2>Scenario assumptions</h2><div className="scenario-tabs">{model.assumptions.map((row) => <button key={row.name} className={selectedScenario === row.name ? "active" : ""} onClick={() => setSelectedScenario(row.name)}>{row.name}</button>)}</div><label><span>Productivity change <strong>{format(active.assumption.productivityChangePercent, "%")}</strong></span><input type="range" min="-50" max="100" step="1" value={active.assumption.productivityChangePercent} onChange={(event) => update("productivityChangePercent", Number(event.target.value))} /></label><label><span>Gang size <strong>{format(active.assumption.gangSize)}</strong></span><input type="number" min="1" step="1" value={active.assumption.gangSize} onChange={(event) => update("gangSize", Math.max(1, Number(event.target.value)))} /></label><label><span>Disruption exposure <strong>{format(active.assumption.disruptionExposurePercent, "%")}</strong></span><input type="range" min="0" max="100" step="1" value={active.assumption.disruptionExposurePercent} onChange={(event) => update("disruptionExposurePercent", Number(event.target.value))} /><small>Adjusted capacity = daily gang output × (1 − exposure). Historical occurrence informs the Current Trend default; it is an editable capacity assumption, not a statistical probability.</small></label><label className="scenario-checkbox"><input type="checkbox" checked={active.assumption.weekendWorking} onChange={(event) => update("weekendWorking", event.target.checked)} /><span>Weekend working ON</span></label></div>
      <div><h2>Indicative forecast comparison</h2><div className="scenario-chart"><ResponsiveContainer width="100%" height="100%"><BarChart data={model.forecasts.map((row) => ({ name: row.assumption.name, variance: row.result.daysEarlyLate ?? 0, available: row.result.available }))}><CartesianGrid strokeDasharray="3 3" vertical={false} /><XAxis dataKey="name" /><YAxis label={{ value: "Working days late (+) / early (−)", angle: -90, position: "insideLeft" }} /><Tooltip /><Bar dataKey="variance" name="Finish variance (working days)">{model.forecasts.map((row) => <Cell key={row.assumption.name} fill={!row.result.available ? "#98a2b3" : (row.result.daysEarlyLate ?? 0) > 0 ? "#d92d20" : "#079455"} />)}</Bar></BarChart></ResponsiveContainer></div></div></section>

    <section className="scenario-table-wrap"><table><thead><tr>{["Scenario", "Productivity", "Gang", "Daily Output", "Disruption", "Remaining Man-Days", "Forecast Working Days", "Forecast Finish", "Early / Late", "vs Current Trend"].map((heading) => <th key={heading}>{heading}</th>)}</tr></thead><tbody>{model.forecasts.map(({ assumption, result }) => <tr key={assumption.name}><td><strong>{assumption.name}</strong></td><td>{format(result.productivity, ` ${activity.unit}/man-day`)}</td><td>{format(result.gangSize)}</td><td>{format(result.adjustedDailyCapacity, ` ${activity.unit}/day`)}</td><td>{format(assumption.disruptionExposurePercent, "% exposure")}</td><td>{format(result.remainingManDays)}</td><td>{format(result.forecastWorkingDays)}</td><td>{result.available ? formatDate(result.forecastFinish) : "Forecast unavailable – insufficient data."}</td><td>{format(result.daysEarlyLate, " working days")}</td><td>{result.forecastFinish && currentFinish ? format(workingDayVariance(result.forecastFinish, currentFinish, assumption.weekendWorking), " working days") : "—"}</td></tr>)}</tbody></table></section>

    <section className="scenario-grid"><article><h2>Recovery requirement</h2>{model.recovery.available ? <dl><div><dt>Remaining working days</dt><dd>{model.recovery.remainingWorkingDays}</dd></div><div><dt>Required Man-Day Productivity</dt><dd>{format(model.recovery.requiredProductivity, ` ${activity.unit}/man-day`)}</dd></div><div><dt>Required Daily Gang Output</dt><dd>{format(model.recovery.requiredDailyOutput, ` ${activity.unit}/day`)}</dd></div><div><dt>Required Average Gang</dt><dd>{format(model.recovery.requiredAverageGangSize)}</dd></div><div><dt>Required improvement</dt><dd>{format(model.recovery.requiredImprovementPercent, "%")}</dd></div><div><dt>Operational gang</dt><dd>Approximately {model.recovery.operationalGangSize} operatives</dd></div></dl> : <p>Recovery requirement unavailable – insufficient remaining time or baseline data.</p>}<p className="scenario-warning">Gang-size scenarios assume additional labour can work productively without congestion or access constraints.</p></article>
      <article><h2>Historical disruption occurrence</h2>{model.disruptionStats.length ? model.disruptionStats.map((row) => <div className="scenario-stat" key={row.category}><strong>{row.category}</strong><span>Historical occurrence rate: {format(row.occurrenceRate === null ? null : row.occurrenceRate * 100, "%")}</span><small>{row.affectedWorkingDays} affected days / {row.relevantWorkingDays} relevant working days · {row.events} events · {format(row.totalLostHours, " lost hours")}</small></div>) : <p>Insufficient disruption history for this activity.</p>}</article>
      <article><h2>Potential downstream programme impact</h2>{model.downstream.length ? model.downstream.map((row) => <div className="scenario-stat" key={`${row.predecessorId}-${row.successorId}`}><strong>{activities.find((item) => item.programmeActivityId === row.successorId)?.activity ?? row.successorId}</strong><span>{row.label}</span><small>{row.type} relationship{row.lag ? ` · imported lag ${row.lag}` : ""}</small></div>) : <p>No direct successor relationships are available. No critical-path impact is inferred.</p>}<p>{model.float.message}</p></article>
      <article><h2>Forecast Basis</h2><dl><div><dt>Data date</dt><dd>{formatDate(dataDate)}</dd></div><div><dt>Actual quantity</dt><dd>{format(model.cumulativeQuantity, ` ${activity.unit}`)}</dd></div><div><dt>Remaining quantity</dt><dd>{format(model.remainingQuantity, ` ${activity.unit}`)}</dd></div><div><dt>Actual productivity period</dt><dd>{model.recent.start ? `${formatDate(model.recent.start)} – ${formatDate(model.recent.finish)} (${model.recent.workingDays} recorded days)` : "No valid recent period"}</dd></div><div><dt>Productivity used</dt><dd>{format(active.result.productivity, ` ${activity.unit}/man-day`)}</dd></div><div><dt>Gang size used</dt><dd>{format(active.assumption.gangSize)}</dd></div><div><dt>Disruption assumption</dt><dd>{format(active.assumption.disruptionExposurePercent, "% capacity exposure")}</dd></div><div><dt>Working calendar</dt><dd>{active.assumption.weekendWorking ? "7-day scenario calendar" : activity.calendar || "Monday–Friday fallback"}</dd></div><div><dt>Planned finish</dt><dd>{formatDate(activity.plannedFinish)}</dd></div></dl></article></section>
    <p className="scenario-disclaimer">All outputs are indicative scenarios based on stated assumptions. They are not certain completion outcomes and do not modify stored SitePulse actuals.</p>
  </div></main>;
}
