"use client";

import { FormEvent, useEffect, useMemo, useRef, useState } from "react";
import * as XLSX from "xlsx";
import { getActiveDate, getActiveProject, getActiveProjectId, loadSiteDay, saveDay, setActiveDate } from "@/lib/storage";
import { loadV2DailyRecords, loadV2Programme, saveV2DailyRecord } from "@/lib/supabase/v2Data";
import { labourControl, parseAttendanceRows, type V2AttendanceRow } from "@/lib/v2Labour";
import { plannedQuantityToDate, v2Productivity, type V2DailyRecord } from "@/lib/v2Productivity";
import type { ProgrammeActivity } from "@/types/site";
import { V2_DEMO_ATTENDANCE } from "@/lib/v2Demo";

type Result = { quantity: number; actual: number | null; earned: number | null; pf: number | null; variance: number };
const display = (value: number | null, digits = 2) => value === null ? "—" : value.toLocaleString("en-GB", { maximumFractionDigits: digits });

export default function DailyUpdatePage() {
  const fileRef = useRef<HTMLInputElement>(null);
  const [activities, setActivities] = useState<ProgrammeActivity[]>([]), [records, setRecords] = useState<V2DailyRecord[]>([]), [attendance, setAttendance] = useState<V2AttendanceRow[]>([]);
  const [date, setDate] = useState(""), [activityId, setActivityId] = useState(""), [men, setMen] = useState(""), [hoursPerMan, setHoursPerMan] = useState(""), [quantity, setQuantity] = useState(""), [affectedHours, setAffectedHours] = useState("");
  const [constrained, setConstrained] = useState(false), [reason, setReason] = useState(""), [note, setNote] = useState(""), [saving, setSaving] = useState(false), [error, setError] = useState(""), [message, setMessage] = useState(""), [result, setResult] = useState<Result | null>(null);
  const hoursPerMd = getActiveProject()?.hoursPerManDay ?? 8;

  useEffect(() => { const selected = getActiveDate(); queueMicrotask(() => setDate(selected)); Promise.all([loadV2Programme(getActiveProjectId()), loadV2DailyRecords(getActiveProjectId())]).then(([programme, daily]) => { const measurable = programme.activities.filter((row) => row.plannedQuantity > 0 && Boolean(row.unit) && Number(row.plannedManDays) > 0); setActivities(programme.activities); setRecords(daily); setActivityId(measurable[0]?.programmeActivityId ?? ""); if (programme.demo) { const existing=loadSiteDay("2026-08-25",getActiveProjectId())??{date:"2026-08-25",attendance:[],crews:[],events:[]};if(!existing.attendanceImport?.length)saveDay({...existing,attendanceImport:V2_DEMO_ATTENDANCE},getActiveProjectId());setAttendance((existing.attendanceImport as V2AttendanceRow[]|undefined)??V2_DEMO_ATTENDANCE);setDate("2026-08-25"); } }).catch((caught) => setError(caught instanceof Error ? caught.message : "Unable to load Daily Update.")); }, []);
  useEffect(() => { if (!date) return; queueMicrotask(() => setAttendance((loadSiteDay(date, getActiveProjectId())?.attendanceImport ?? []) as V2AttendanceRow[])); }, [date]);

  const activity = useMemo(() => activities.find((row) => row.programmeActivityId === activityId), [activities, activityId]);
  const dayRecords = useMemo(() => records.filter((row) => row.date === date), [date, records]);
  const control = useMemo(() => labourControl(attendance, dayRecords.reduce((sum, row) => sum + row.labourHours, 0), hoursPerMd), [attendance, dayRecords, hoursPerMd]);
  const labourHours = Math.max(0, Number(men) * Number(hoursPerMan));
  const warnings = [!attendance.length ? "No sign-in sheet exists for this date. This allocation will be labelled Manual labour entry." : "", control.unallocatedHours > 0 ? `${display(control.unallocatedHours)} attendance hours remain unallocated.` : "", control.unallocatedHours < 0 ? `Allocations exceed attendance by ${display(Math.abs(control.unallocatedHours))} hours.` : "", labourHours > 0 && Number(quantity) === 0 ? "Labour is allocated without a completed quantity." : "", Number(quantity) > 0 && !(labourHours > 0) ? "Completed quantity has been entered without labour." : ""].filter(Boolean);

  async function importSheet(file?: File) {
    if (!file) return; setError(""); setMessage("");
    try { const workbook = XLSX.read(await file.arrayBuffer(), { type: "array", cellDates: true }); const sheet = workbook.Sheets[workbook.SheetNames[0]]; const parsed = parseAttendanceRows(sheet ? XLSX.utils.sheet_to_json<Record<string, unknown>>(sheet, { defval: "", raw: true }) : []); if (!parsed.attendance.length) throw new Error(parsed.issues[0]?.message || "No valid attendance rows were found."); const grouped = new Map<string, V2AttendanceRow[]>(); parsed.attendance.forEach((row) => grouped.set(row.date, [...(grouped.get(row.date) ?? []), row])); grouped.forEach((rows, workDate) => { const existing = loadSiteDay(workDate, getActiveProjectId()) ?? { date: workDate, attendance: [], crews: [], events: [] }; saveDay({ ...existing, attendanceImport: rows }, getActiveProjectId()); }); setAttendance(grouped.get(date) ?? []); setMessage(`${parsed.attendance.length} attendance rows imported${parsed.issues.length ? ` · ${parsed.issues.length} excluded` : ""}.`); }
    catch (caught) { setError(caught instanceof Error ? caught.message : "Unable to import the sign-in sheet."); }
    finally { if (fileRef.current) fileRef.current.value = ""; }
  }

  async function submit(event: FormEvent) {
    event.preventDefault(); if (!activity) return setError("Select a productivity-ready programme activity."); const enteredQuantity = Number(quantity); const enteredMen = Number(men); const enteredHours = Number(hoursPerMan); const standing = Number(affectedHours || 0);
    if (!(enteredMen > 0) || !(enteredHours > 0) || !(enteredQuantity >= 0)) return setError("Enter valid men, hours per man and completed quantity."); if (standing < 0 || standing > labourHours) return setError("Affected or standing hours must be within the allocated labour hours."); if (constrained && !reason.trim()) return setError("Enter the constraint reason."); if (attendance.length && labourHours > Math.max(0, control.unallocatedHours) + .001) return setError(`Only ${display(Math.max(0, control.unallocatedHours))} attendance hours remain available to allocate.`);
    setSaving(true); setError(""); setMessage(""); setResult(null);
    try { const record = { date, quantity: enteredQuantity, labourHours, men: enteredMen, affectedHours: standing || undefined, manualLabour: !attendance.length, constrained, constraintReason: reason.trim() || undefined, note: `${!attendance.length ? "Manual labour entry. " : ""}${note.trim()}`.trim() || undefined }; const id = await saveV2DailyRecord(getActiveProjectId(), activity, record); const saved = { id, activityId, ...record }; const next = [...records, saved]; setRecords(next); setActiveDate(date); const cumulative = next.filter((row) => row.activityId === activityId && row.date <= date).reduce((sum, row) => sum + row.quantity, 0); const metrics = v2Productivity(activity, enteredQuantity, labourHours, hoursPerMd); setResult({ quantity: enteredQuantity, actual: metrics.actualManDays, earned: metrics.earnedManDays, pf: metrics.productivityFactor, variance: cumulative - plannedQuantityToDate(activity, date) }); setQuantity(""); setMen(""); setHoursPerMan(""); setAffectedHours(""); setNote(""); setConstrained(false); setReason(""); }
    catch (caught) { setError(caught instanceof Error ? caught.message : "Unable to save daily allocation."); } finally { setSaving(false); }
  }

  return <main className="v2-page v2-form-page"><header className="v2-hero"><div><p className="eyebrow">Daily Update</p><h1>Allocate today&apos;s labour</h1><p>Attendance is the daily control total. Allocate it directly to programme activities.</p></div></header>
    <section className="v2-panel v2-attendance-control"><div className="v2-panel-heading"><label>Date<input type="date" value={date} onChange={(event) => { setDate(event.target.value); setActiveDate(event.target.value); }} /></label><label className="secondary-button">Import sign-in sheet<input ref={fileRef} hidden type="file" accept=".xlsx,.xls" onChange={(event) => void importSheet(event.target.files?.[0])} /></label></div><strong>{control.men} men · {display(control.attendanceHours)} attendance hours · {display(control.allocatedHours)} allocated · {display(control.unallocatedHours)} unallocated</strong><small>{attendance.length ? `Imported attendance · ${display(control.signedInMd)} actual signed-in MD` : "No imported sign-in sheet"}</small></section>
    {message && <p className="dashboard-notice" role="status">{message}</p>}
    <form className="v2-panel v2-daily-form" onSubmit={submit}><label className="v2-field-wide">Programme activity<select required value={activityId} onChange={(event) => setActivityId(event.target.value)}><option value="">Select activity</option>{activities.filter((row) => row.plannedQuantity > 0 && Boolean(row.unit) && Number(row.plannedManDays) > 0).map((row) => <option key={row.id} value={row.programmeActivityId}>{row.activityName || row.activity} · {row.elevation} {row.level}</option>)}</select></label>
      {activity && <div className="v2-activity-context v2-field-wide"><span>Planned: {activity.plannedQuantity} {activity.unit}</span><span>Budget: {display(activity.plannedManDays ?? null)} MD</span><span>Target: {display(v2Productivity(activity, 0, 0, hoursPerMd).targetProductivity)} {activity.unit}/MD</span></div>}
      <label>Men allocated<input required min="1" step="1" type="number" inputMode="numeric" value={men} onChange={(event) => setMen(event.target.value)} /></label><label>Hours per man<input required min="0.01" step="any" type="number" inputMode="decimal" value={hoursPerMan} onChange={(event) => setHoursPerMan(event.target.value)} /></label><div className="v2-calculated"><span>Allocated labour</span><strong>{display(labourHours)} hours · {display(labourHours / hoursPerMd)} MD</strong><small>{attendance.length ? "From imported attendance allocation" : "Manual labour entry"}</small></div><label>Quantity completed<input required min="0" step="any" type="number" inputMode="decimal" value={quantity} onChange={(event) => setQuantity(event.target.value)} /></label><label>Affected / standing hours <small>Optional</small><input min="0" max={labourHours || undefined} step="any" type="number" value={affectedHours} onChange={(event) => setAffectedHours(event.target.value)} /></label>
      <fieldset className="v2-field-wide"><legend>Was the work constrained?</legend><label className="v2-check"><input type="checkbox" checked={constrained} onChange={(event) => setConstrained(event.target.checked)} /> Yes</label></fieldset>{constrained && <label className="v2-field-wide">Constraint reason<input required maxLength={160} value={reason} onChange={(event) => setReason(event.target.value)} /></label>}<label className="v2-field-wide">Note <small>Optional</small><textarea maxLength={300} value={note} onChange={(event) => setNote(event.target.value)} rows={3} /></label>
      {warnings.length > 0 && <ul className="v2-warnings v2-field-wide">{warnings.map((warning) => <li key={warning}>{warning}</li>)}</ul>}{error && <p className="dashboard-notice error v2-field-wide" role="alert">{error}</p>}<button className="primary-button v2-primary-action v2-field-wide" type="submit" disabled={saving}>{saving ? "Saving…" : "Save daily allocation"}</button></form>
    {result && <section className="v2-panel v2-result" aria-live="polite"><p className="eyebrow">Allocation saved</p><h2>Activity result</h2><dl><div><dt>Quantity achieved</dt><dd>{display(result.quantity)}</dd></div><div><dt>Actual MD</dt><dd>{display(result.actual)}</dd></div><div><dt>Earned MD</dt><dd>{display(result.earned)}</dd></div><div><dt>Daily PF</dt><dd>{display(result.pf)}</dd></div></dl><strong className={result.variance >= 0 ? "v2-positive" : "v2-negative"}>{result.variance >= 0 ? "Ahead" : "Behind"} programme by {display(Math.abs(result.variance))} {activity?.unit || "units"}</strong><p>{display(labourControl(attendance, control.allocatedHours + labourHours, hoursPerMd).unallocatedHours)} attendance hours remain unallocated.</p></section>}
  </main>;
}
